export const members = [
  { name: "주장권", part: "web" },
  { name: "김예린", part: "web" },
  { name: "김동찬", part: "web" },
  { name: "이지원", part: "web" },
  { name: "이윤아", part: "web" },
  { name: "이인철", part: "web" },
  { name: "정우용", part: "web" },
  { name: "이만재", part: "web" },
  { name: "박예은", part: "web" },
  { name: "박지섭", part: "web" },
  { name: "김영현", part: "web" },
  { name: "김주하", part: "web" },

  { name: "차지용", part: "app" },
  { name: "박석진", part: "app" },
  { name: "남궁혜민", part: "app" },
  { name: "장대영", part: "app" },

  { name: "현진용", part: "server" },
  { name: "이기연", part: "server" },
  { name: "오동재", part: "server" },
  { name: "김석완", part: "server" },
  { name: "김우진", part: "server" },
  { name: "김동균", part: "server" },
  { name: "조용현", part: "server" },
  { name: "안준영", part: "server" },
  { name: "최인호", part: "server" },
  { name: "김이화", part: "server" },
  { name: "최민우", part: "server" },
  { name: "김나윤", part: "server" },
  { name: "이승창", part: "server" },
  { name: "박소정", part: "server" },
  { name: "김예은", part: "server" },
  { name: "이길수", part: "server" },
  { name: "정윤선", part: "server" },

  { name: "고은경", part: "pm" },
  { name: "김보정", part: "pm" },
  { name: "김신희", part: "pm" },
  { name: "박세연", part: "pm" },
  { name: "서해근", part: "pm" },
  { name: "송다은", part: "pm" },
  { name: "윤지원", part: "pm" },
  { name: "이수현", part: "pm" },
  { name: "최지수", part: "pm" },
  { name: "임민지", part: "pm" },

  { name: "김규빈", part: "ai" },
  { name: "나현호", part: "ai" },
  { name: "박무재", part: "ai" },
  { name: "안지호", part: "ai" },
  { name: "이상민", part: "ai" },
  { name: "전영욱", part: "ai" },
];